### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by lukeed** [tj/luna#83]
I hate to be the one to bring this up (lol)... but is there a set of benchmarks somewhere that could be comparable to other C / Erlang / Go setups?

Very intrigued, but admittedly also curious how it stacks up against others.

Thanks!

**Comment by vendethiel** [comment]
What

**Comment by lukeed** [comment]
...just wondering how "fast" Luna is

**Comment by glhrmfrts** [comment]
Luna doesn't run any code yet, it only parses the code to an AST. There is a VM in there but it's very primitive and it will most likely be completely refactored in the future, just like the code generation.

**Comment by lukeed** [comment]
Ah, ok. Thank you for the clarification @glhrmfrts !
