### ISSUE TITLE
Missing image on installer

### ISSUE THREAD

**Issue by PhilipChani** [tj/luna#99]
Am installing luna studio 1.2 beta but get an error every time at 80% download progress
![luna error](https://user-images.githubusercontent.com/26784387/37028429-e5e62b70-213c-11e8-83d2-10695b2dc419.png)

**Comment by vendethiel** [comment]
wrong repo.

if you did read the description:

![image](https://user-images.githubusercontent.com/199499/37028638-21500de6-2135-11e8-9404-26c6b83a5f0f.png)

**Comment by PhilipChani** [comment]
Dint notice, let me fix that
